### PR TITLE
Ubuntu server

### PR DESCRIPTION
**Pull request by david-okeefe**
Added instructions for installing and configuring FHClient on Ubuntu server for #13

### CODE REVIEW

**Comment by likamrat** [comment]
@david-okeefe looks good. Do you mind adding a bullet point pointing to this guide in the main README under MacOS installation?

**Comment by david-okeefe** [comment]
I added a link in the main README

**Review by likamrat — COMMENTED** [review]
"I have an Ubuntu Server which I want to use and start folding"
WDYT?

**Comment by david-okeefe** [comment]
> "I have an Ubuntu Server which I want to use and start folding"
> WDYT?

Works for me.  I updated the README with the proposed text.

**Pull request merged**
