### PR TITLE
cloud-init Ubuntu 18.04 F@H install

### PR DESCRIPTION
**Pull request by bleemus**
This cloud-init script was based off your shell script, perks include the ability to spin up a VMSS from it.  We can combine your ARM template with the CustomData field potentially.

### CODE REVIEW

**Comment by bleemus** [comment]
added GCP info

**Review by likamrat — COMMENTED** [review]
@david-okeefe @chmitch can you please give this a go?

**Comment by bleemus** [comment]
Looks like the AWS cloud-init isn't working, will be troubleshooting

**Comment by bleemus** [comment]
After a few hours of diving around in docs and configs... Turns out the `users` in the cloudinit overrides any users in AWS/Ubuntu, adding -default keeps the default ubuntu user around and allows for everything else to run successfully!

**Pull request closed without merging**
